### ISSUE TITLE
Object's 3D coordinates needed in the root reference frame

### ISSUE THREAD

**Issue by pattacini** [robotology/r1-grasping#3]
We need to get the reconstructed 3D position in the root reference frame rather than camera's frame, as it seems the case from OPC's content inspection.

**Comment by jchevrie** [comment]
The problem comes from a missing connection between `/vision3d-gateway/cam:rpc` and `/depthCamera/rpc:i`, which is used to retrieve the intrinsic parameters for the calibration of the camera.

Everything works correctly after adding this connection.
